### ISSUE TITLE
Make api call getEventsForCommunity take in a userId

### ISSUE THREAD

**Issue by lfvarela** [StanfordCS194/volunta#98]

**Comment by susannahameyer** [comment]
should it take in a community reference object instead of id?

**Comment by lfvarela** [comment]
I was thinking it should take a userId, get the users community and go from there, but it could also take in a community ref. Whatever works, I said this since the following line is in the function: 

  const currentUserCommunityRef = await getUserCommunity(c.TEST_USER_ID);

So it would make sense just to switch it to taking in a user.

**Comment by susannahameyer** [comment]
kk! i think we should have it take in the ref since a bunch of other things in the community also use it (getCommunityName, getCommunityCoverPhoto, and getUsersAttributes all use it), so if we use the ID then we end up re-fetching that anyway. will do soon

**Comment by lfvarela** [comment]
Sure!
